version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bingo
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always